name: Keep bot alive
on: 
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: 
jobs: 
  ping:
    runs-on: ubuntu-latest
    env:
      PING_URL: ${{ secrets.PING_URL }}
    steps:
    - name: Ping app with retry
      run: |
        echo "Pinging Flask app..."
        for i in {1..3}; do
          echo "Attempt $i..." 
          STATUS=$(curl --max-time 180 -s -o /dev/null -w "%{http_code}" "$PING_URL")
          if [ "$STATUS" -eq 200 ]; then
            echo "Success with 200 OK"
            exit 0
          fi
          echo "Failed with status $STATUS, retrying in 15s..."
          sleep 15
        done

        echo "All attempts failed"
        exit 1
                
